### ISSUE TITLE
how to make activator give % chance to perform actions

### ISSUE THREAD

**Issue by stylinnile** [ssomar1607/ExecutableItems#11]
I'm trying to make a potion that has a 50% to give all positive effects and a 50% chance to give all negative effects but after combing through the wiki I cant find a way to do it. is there a way to do this? thanks

**Comment by ssomar1607** [comment]
Join my discord next time. 

https://github.com/ssomar1607/ExecutableItems/wiki/%E2%9E%A4-Commands#random-run
